services:
  fastapi:
    build:
      context: .
      dockerfile: ./fastapi/Dockerfile/local/Dockerfile
    container_name:
      fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/fastapi
    env_file:
      - .envs/local/postgres
    depends_on:
      - postgres
    
  postgres:
    # image: postgres:15
    build:
      context: .
      dockerfile: ./postgres/Dockerfile/local/Dockerfile
    container_name:
      postgresql
    ports:
      - "5432:5432"
    env_file:
      - .envs/local/postgres
    volumes:
      - fastapi01_postgres_data:/var/lib/postgresql/data
    # context: ./postgres ←必要あればカスタムイメージに切替可能

volumes:
  fastapi01_postgres_data:
